### ISSUE TITLE
Added source does not show up in lamindb instance

### ISSUE THREAD

**Issue by mossjacob** [laminlabs/bionty#152]
### Report

I'm using LaminDB and want to add a source to bionty.

[Following the docs](https://bionty-base.lamin.ai/guide/config) I've added to my `sources_local.yaml` file the following:
```
...
Tissue:
  po:
    plants:
      '2024-04-17':
        url: https://purl.obolibrary.org/obo/po/releases/2024-04-17/po.owl
    name: Plant ontology
    website: https://obofoundry.org/ontology/po.html
  uberon:
...
```

When I run `bt.base.display_currently_used_sources()` my new source doesn't show up. I think this is because it looks in the file `.lamindb_current_sources.yaml` instead of my `sources_local.yaml` file when using lamindb. It does show up when I run `bt.base.display_available_sources()` but this is because that method uses the `sources_local.yaml` file. How can I get this to work with LaminDB?

I'm using the versions:

```
lamin-utils                        0.13.7         Lamin Utils.
lamindb                            0.76.15        A data framework for biol...
lamindb-setup                      0.80.0         Setup & configure LaminDB.
bionty                             0.51.2         Registries for basic biol...
```
