### ISSUE TITLE
♻ Refactor `sources.yaml` to enable flexible versions

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty#238]
Instead of:
```
Organism:
  ensembl:
    vertebrates:
      release-112:
        url: https://ftp.ensembl.org/pub/release-112/species_EnsemblVertebrates.txt
      release-111:
        url: https://ftp.ensembl.org/pub/release-111/species_EnsemblVertebrates.txt
      release-110:
        url: https://ftp.ensembl.org/pub/release-110/species_EnsemblVertebrates.txt
      release-109:
        url: https://ftp.ensembl.org/pub/release-109/species_EnsemblVertebrates.txt
      release-108:
        url: https://ftp.ensembl.org/pub/release-108/species_EnsemblVertebrates.txt
  name: Ensembl
  website: https://www.ensembl.org
```

Have something like:
```
Organism:
  ensembl:
    vertebrates:
      latest_version: release-112
  url: https://ftp.ensembl.org/pub/<version>/species_EnsemblVertebrates.txt
  name: Ensembl
  website: https://www.ensembl.org
```

This will enable users to use any version independent of `latest_version` we support (on `s3://bionty-assets`) by default.
